version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URL=mongodb+srv://TruongSon:0918318110@cluster0.lzuskd0.mongodb.net/TheGioiXe?retryWrites=true&w=majority&appName=Cluster0
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend


